### ISSUE TITLE
TypeError: Cannot read property 'baseVal' of undefined

### ISSUE THREAD

**Issue by aarthi0808** [d3/d3#1545]
Whie creating d3 chart with Node js,it throws following error

var t = g.transform.baseVal.consolidate();

TypeError: Cannot read property 'baseVal' of undefined
at d3.transform (file:///Users/administrator/Downloads/nodejs/d3.js:5347:28)
at Object.d3.transform (file:///Users/administrator/Downloads/nodejs/d3.js:5350:7)
at d3_interpolateTransform (file:///Users/administrator/Downloads/nodejs/d3.js:5394:35)
at Object. (file:///Users/administrator/Downloads/nodejs/d3.js:7697:32)
at d3_Map. (file:///Users/administrator/Downloads/nodejs/d3.js:7858:31)
at d3_Map.d3_class.forEach (file:///Users/administrator/Downloads/nodejs/d3.js:271:13)
at start (file:///Users/administrator/Downloads/nodejs/d3.js:7857:28)
at Object.callback (file:///Users/administrator/Downloads/nodejs/d3.js:7851:38)
at d3_timer_mark (file:///Users/administrator/Downloads/nodejs/d3.js:2075:80)
at d3_timer_step as _onTimeout

**Comment by bamthomas** [comment]
I'm in the same situation than @andrewminer 

@jasondavies what would be your advice to be able test pages that includes SVG/d3 components from library that is  not in the codebase?
Disable them in the tests by config (dotenv or whatever)?

**Comment by jasondavies** [comment]
It's been 9 years since this issue was originally discussed. Things have changed since then. :)

I don't see any issue using [JSDOM](https://github.com/jsdom/jsdom) either for testing, as done by [d3-selection](https://github.com/d3/d3-selection/tree/main/test), or for server-side rendering.

**Comment by bamthomas** [comment]
sorry @jasondavies for not having looked at the dates.
I'm going see how d3-selection is doing.
