### ISSUE TITLE
npm install --save d3 ERR! Tried to download(undefined..

### ISSUE THREAD

**Issue by unstephenk** [d3/d3#3115]
Just tried to install d3 and the typings using the following commands:
npm install --save d3
npm install --save-dev @types/d3

I am on the following versions:
npm 5.1.0
node 7.9.0

This is the error I got:
```
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@7.9.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:188:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64"
gyp ERR! cwd /Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/7.9.0/bin/node /Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node --module_name=fse --module_path=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents
node-pre-gyp ERR! node -v v7.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/7.9.0/bin/node /Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node --module_name=fse --module_path=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ d3@4.9.1
added 114 packages and updated 1 package in 25.171s
```

**Comment by geekplux** [comment]
If you on windows machine run `npm install -g node-pre-gyp` command in the terminal as administrator.

**Comment by curran** [comment]
This seems not to be an error caused by D3, but rather something else in your Node environment. Are you on Windows?

**Comment by unstephenk** [comment]
Tried `npm install -g -node-pre-gyp` but still got errors:

```
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@7.9.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:188:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64"
gyp ERR! cwd /Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/7.9.0/bin/node /Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node --module_name=fse --module_path=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents
node-pre-gyp ERR! node -v v7.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/7.9.0/bin/node /Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node --module_name=fse --module_path=/Users/ahe453/Dev/websites/Eye-in-the-sky-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ d3@4.9.1
added 114 packages and updated 1 package in 18.645s
```
I am currently on a Macbook. What could be the cause of this issue?

**Comment by unstephenk** [comment]
FIXED IT!
installed node 8.1.3
`sudo npm install -g node-pre-gyp`
`sudo npm install --save d3`
`sudo npm install --save-dev @types/d3`

No errors after that. Thanks!

**Comment by unstephenk** [comment]
FIXED IT!
installed node 8.1.3
sudo npm install -g node-pre-gyp
sudo npm install --save d3
sudo npm install --save-dev @types/d3

No errors after that. Thanks!
