### ISSUE TITLE
d3 4.13 build fails with rollup 1.x

### ISSUE THREAD

**Issue by pravi** [d3/d3#3352]
We are trying to update rollup to 1.x version in debian (we try to have only one version of a library/tool to reduce the maintenance burden). All d3-* modules still builds fine but d3 4.13 itself fails with this error.

```
/<<PKGBUILDDIR>>/build/d3.node.js:1
undefinedObject.defineProperty(exports, "event", {get: function() { return d3Selection.event; }});
^

ReferenceError: undefinedObject is not defined
    at Object.<anonymous> (/<<PKGBUILDDIR>>/build/d3.node.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/<<PKGBUILDDIR>>/test/d3-test.js:2:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```
We are happy to update d3 to 5.12, which builds fine with rollup 1.x (1.10.1), but dagre-d3-renderer still wants 4.13.0 as peer dependency and yarn install fails for gitlab. Here is the discussion with gitlab about updating d3 to 5.12, https://gitlab.com/gitlab-org/gitlab/issues/33944

While the best option would be fixing dagre-d3-renderer, it seems that project is not very active. Would it be possible to release a 4.x version that builds with rollup 1.x?

**Comment by mbostock** [comment]
Sorry, that’s not something I can help with.
